/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AcceptedResponse { 
    /**
     * ID of the accepted message (echoed from the request).
     */
    messageId: string;
    /**
     * The Server has durably taken ownership of the message.
     */
    status: AcceptedResponseStatusEnum;
    /**
     * Epoch milliseconds at which this Server process started. A changed value across responses signals a restart, after which the client re-submits its unconfirmed outbox messages.
     */
    serverStartedAt?: number;
}
export enum AcceptedResponseStatusEnum {
    Accepted = 'accepted'
};



