/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientMessageAck } from './clientMessageAck';


export interface AckMessagePayload { 
    action: AckMessagePayloadActionEnum;
    data: ClientMessageAck;
}
export enum AckMessagePayloadActionEnum {
    AckMessage = 'ackMessage'
};



