/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageAcknowledgement } from './messageAcknowledgement';


export interface AckMessagePayload { 
    action: AckMessagePayloadActionEnum;
    data: MessageAcknowledgement;
}
export enum AckMessagePayloadActionEnum {
    AckMessage = 'ackMessage'
};



