/**
 * Fourletters API - Authentication
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthRequest { 
    /**
     * The identity token provided by the third-party OAuth provider.
     */
    token: string;
}

