/**
 * Fourletters API - Authentication
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponse } from './userResponse';


export interface AuthResponse { 
    /**
     * The short-lived JWT Access Token.
     */
    access_token: string;
    user: UserResponse;
}

