/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthRequest { 
    /**
     * The identity token provided by the third-party OAuth provider. This is the security anchor and is always verified server-side (VK id_token, Google credential).
     */
    token: string;
    /**
     * Optional client-supplied first name. Used for presentation only when the verified provider returns masked profile data (e.g. VK public_info). Never used for authentication.
     */
    firstName?: string;
    /**
     * Optional client-supplied last name. Used for presentation only; never used for authentication.
     */
    lastName?: string;
    /**
     * Optional client-supplied avatar URL. Used for presentation only; never used for authentication.
     */
    avatarUrl?: string;
}

