/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Hub -> client: an ephemeral call signal from a call peer.
 */
export interface CallSignalEvent { 
    type: CallSignalEventTypeEnum;
    /**
     * The call peer that sent the signal, stamped by the sender\'s Hub from its authenticated session.
     */
    senderId: string;
    /**
     * E2E encrypted call signal, relayed unaltered from the CallSignalCommand.
     */
    payload: string;
}
export enum CallSignalEventTypeEnum {
    CallSignal = 'call_signal'
};



