/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Client -> Hub: an ephemeral call signal (ringing, answer, ICE candidates, hangup, decline, busy) for a 1:1 call.
 */
export interface CallSignalCommand { 
    type: CallSignalCommandTypeEnum;
    /**
     * The call peer this signal is addressed to.
     */
    recipientId: string;
    /**
     * E2E encrypted call signal over the pairwise Double Ratchet. Format \'<sessionType>.<bodyBase64>\', as for a 1:1 EncryptedMessage payload.
     */
    payload: string;
}
export enum CallSignalCommandTypeEnum {
    CallSignal = 'call_signal'
};



