/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientMessageAck { 
    /**
     * ID of the message being acknowledged
     */
    messageId: string;
    /**
     * ID of the user who originally sent the message (used for returning the read receipt)
     */
    senderId: string;
}

