/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WrappedGroupKey } from './wrappedGroupKey';


/**
 * Creates a group with the caller as owner and an initial epoch-0 key set wrapped to every member.
 */
export interface CreateGroupRequest { 
    /**
     * Group name (plaintext).
     */
    name: string;
    /**
     * Initial member user ids (the owner is added automatically if omitted).
     */
    members: Array<string>;
    /**
     * Epoch-0 group key wrapped to every initial member (including the owner).
     */
    keys: Array<WrappedGroupKey>;
}

