/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Creates a group with the caller as owner and the given initial roster.
 */
export interface CreateGroupRequest { 
    /**
     * Group name (plaintext).
     */
    name: string;
    /**
     * Initial member user ids (the owner is added automatically if omitted).
     */
    members: string[];
}

