/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptType } from './receiptType';


export interface DeliveryReceipt { 
    /**
     * ID of the message being acknowledged.
     */
    messageId: string;
    /**
     * ID of the original message\'s sender — the party to notify. Echoed by the recipient from the received message so the Server can relay this receipt 
     */
    originalSenderId?: string;
    type: ReceiptType;
    /**
     * Signature over (messageId, type, originalSenderId) by the recipient\'s identity key (Base64). Lets the original sender trust the receipt without trusting any Hub.
     */
    signature: string;
}



