/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeliveryReceipt { 
    /**
     * ID of the message being acknowledged.
     */
    messageId: string;
    /**
     * \'delivered\' = the recipient device received and decrypted it; \'read\' = the user opened it.
     */
    type: DeliveryReceiptTypeEnum;
    /**
     * Signature over (messageId, type) by the recipient\'s identity key (Base64). Lets the Server and the original sender trust the receipt without trusting any Hub.
     */
    signature: string;
}
export enum DeliveryReceiptTypeEnum {
    Delivered = 'delivered',
    Read = 'read'
};



