/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EncryptedMessage { 
    /**
     * Unique identifier for the message generated by the client
     */
    messageId: string;
    /**
     * ID of the recipient user
     */
    recipientId: string;
    /**
     * ID of the sender user (populated by the Hub before delivery)
     */
    senderId?: string;
    /**
     * E2E encrypted message payload (Base64)
     */
    payload: string;
}

