/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EncryptedMessage { 
    /**
     * Unique identifier for the message generated by the client
     */
    messageId: string;
    /**
     * ID of the recipient user
     */
    recipientId: string;
    /**
     * ID of the sender user. Set by the Server from the authenticated session at send time; any client-provided value is ignored. Omitted in the send request.
     */
    senderId?: string;
    /**
     * E2E encrypted message payload (Base64)
     */
    payload: string;
    /**
     * Detached signature over the payload produced by the sender\'s identity key (Base64). Verified end-to-end by the recipient against the public-key directory.
     */
    signature: string;
}

