/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EncryptedMessage { 
    /**
     * Unique identifier for the message generated by the client
     */
    messageId: string;
    /**
     * ID of the recipient user
     */
    recipientId: string;
    /**
     * ID of the sender user. Set by the Server from the authenticated session at send time; any client-provided value is ignored. Omitted in the send request.
     */
    senderId?: string;
    /**
     * E2E encrypted Signal ciphertext. Format \'<sessionType>.<bodyBase64>\' where sessionType is 1 (WhisperMessage, established session) or 3 (PreKeyWhisperMessage, establishes the session). The Server treats it as opaque.
     */
    payload: string;
    /**
     * Present only for group messages. Identifies the group so the recipient threads the message into the group conversation. The sender encrypts and sends one independent 1:1 copy per member; the Server treats each copy as an ordinary 1:1 message. Omitted for 1:1 messages.
     */
    groupId?: string;
}

