/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventMessageReceipt { 
    /**
     * ID of the outgoing message that triggered the event (dispatch or read)
     */
    messageId: string;
}

