/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupKeyNotification } from './groupKeyNotification';


/**
 * WS push: a content-free nudge that a group\'s key rotated to a new epoch. The member refetches its wrapped key (live blob, GET /groups/{id}/keys, or the next /inbox groupKeys pull). The group key itself is never carried over this channel.
 */
export interface GroupKeyEvent { 
    event: GroupKeyEventEventEnum;
    data: GroupKeyNotification;
}
export enum GroupKeyEventEventEnum {
    GroupKeyRotated = 'groupKeyRotated'
};



