/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payload of a groupKeyRotated WS event.
 */
export interface GroupKeyNotification { 
    /**
     * The group whose key rotated.
     */
    groupId: string;
    /**
     * The new current epoch.
     */
    epoch: number;
}

