/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupMember } from './groupMember';


/**
 * A group conversation. The Server owns the roster and the current epoch number but never the group key (it only relays opaque wrapped key blobs).
 */
export interface Group { 
    /**
     * Server-assigned group identifier.
     */
    id: string;
    /**
     * Human-readable group name (stored in plaintext server-side).
     */
    name: string;
    /**
     * The group owner — the sole party permitted to change the roster and publish rotations.
     */
    ownerId: string;
    /**
     * The current group-key epoch (version). Incremented on every rotation (membership change or owner-initiated rekey).
     */
    epoch: number;
    /**
     * The current roster.
     */
    members: Array<GroupMember>;
    /**
     * Epoch milliseconds when the group was created.
     */
    createdAt?: number;
    /**
     * Epoch milliseconds of the last roster/epoch change.
     */
    updatedAt?: number;
}

