/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A member of a group.
 */
export interface GroupMember { 
    /**
     * The member\'s user id.
     */
    userId: string;
    /**
     * Epoch milliseconds when the member joined the group.
     */
    joinedAt?: number;
}

