/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupMember } from './groupMember';


/**
 * A group conversation. The Server owns the roster; messages are sent as one independent 1:1 copy per member, so the Server never holds any group key material.
 */
export interface Group { 
    /**
     * Server-assigned group identifier.
     */
    id: string;
    /**
     * Human-readable group name (stored in plaintext server-side).
     */
    name: string;
    /**
     * The group owner — the sole party permitted to change the roster.
     */
    ownerId: string;
    /**
     * The current roster.
     */
    members: GroupMember[];
    /**
     * Epoch milliseconds when the group was created.
     */
    createdAt?: number;
    /**
     * Epoch milliseconds of the last roster change.
     */
    updatedAt?: number;
}

