/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A single member\'s wrapped group key for one epoch — what the caller pulls to obtain a key it is missing.
 */
export interface GroupKeySet { 
    /**
     * The group this key belongs to.
     */
    groupId: string;
    /**
     * The epoch this wrapped key is for.
     */
    epoch: number;
    /**
     * The group epoch key wrapped to the caller\'s encryption key (Base64).
     */
    wrappedKey: string;
}

