/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lightweight group descriptor for list views.
 */
export interface GroupSummary { 
    id: string;
    name: string;
    ownerId: string;
    /**
     * Server-authoritative Sender-Key epoch.
     */
    epoch?: number;
}

