/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WrappedGroupKey } from './wrappedGroupKey';


/**
 * A complete set of wrapped group keys for one epoch, one entry per member. Generated client-side on create/rotation and posted to the Server, which relays the blobs and advances the roster epoch (compare-and-swap).
 */
export interface GroupKeyDistribution { 
    /**
     * The epoch these wrapped keys belong to. On rotation this must equal the group\'s current epoch + 1; the write is rejected (409) if the current epoch is not exactly the prior value.
     */
    epoch: number;
    /**
     * One wrapped key per member of the (post-change) roster. The Server validates the set covers exactly the roster.
     */
    keys: Array<WrappedGroupKey>;
}

