/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sent by a Hub to the Server on boot to obtain its relay queue. Authentication is via the registration bearer token (a shared secret in Phase 1; a dashboard-issued per-Hub token later). The body itself carries no trust.
 */
export interface HubRegistrationRequest { 
    /**
     * Optional Hub-chosen instance label reported for diagnostics/dashboard display only. The Server does not derive identity or trust from it; the authoritative hubId is assigned by the Server.
     */
    instanceId?: string;
}

