/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HubRegistrationResponse { 
    /**
     * Server-assigned identifier for this Hub registration. Names the Hub\'s queue and (in the volunteer phase) ties it to an owner for accountability and revocation.
     */
    hubId: string;
    /**
     * Name of the auto-delete queue the Server provisioned for this Hub. The Hub binds user routing keys to it and consumes it; the Hub never declares queues itself.
     */
    queueName: string;
    /**
     * Name of the topic exchange the Hub binds user routing keys against (messages.exchange).
     */
    exchange: string;
}

