/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EncryptedMessage } from './encryptedMessage';


export interface InboxResponse { 
    /**
     * The recipient\'s undelivered messages, in arrival order.
     */
    messages: Array<EncryptedMessage>;
    /**
     * Epoch milliseconds at which this Server process started. A changed value across responses signals a restart, after which the client re-submits its unconfirmed outbox messages.
     */
    serverStartedAt?: number;
}

