/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicKeySet } from './publicKeySet';


export interface KeysResponse { 
    /**
     * The user id these public keys belong to.
     */
    userId: string;
    keys: PublicKeySet;
}

