/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OneTimePreKeyDto } from './oneTimePreKeyDto';
import { SignedPreKeyDto } from './signedPreKeyDto';


/**
 * Uploads the caller\'s Signal pre-key bundle (identity, registration id, signed pre-key, and a pool of one-time pre-keys), replacing any previous bundle. Sent on first login of a new device.
 */
export interface KeysUploadRequest { 
    /**
     * The caller\'s Signal registration id.
     */
    registrationId: number;
    /**
     * The caller\'s long-lived Curve25519 identity public key (Base64).
     */
    identityKey: string;
    signedPreKey: SignedPreKeyDto;
    /**
     * Initial pool of one-time pre-keys; the server hands one out per session and deletes it.
     */
    oneTimePreKeys: OneTimePreKeyDto[];
}

