/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KeysUploadRequest { 
    /**
     * The caller\'s ECDSA P-256 public signing key (Base64 SPKI).
     */
    signingPublicKey: string;
    /**
     * The caller\'s ECDH P-256 public encryption key (Base64 SPKI).
     */
    encryptionPublicKey: string;
}

