/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventMessageReceipt } from './eventMessageReceipt';


export interface MessageReadPayload { 
    event: MessageReadPayloadEventEnum;
    data: EventMessageReceipt;
}
export enum MessageReadPayloadEventEnum {
    MessageRead = 'messageRead'
};



