/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptType } from './receiptType';


/**
 * A delivery/read acknowledgement for a message the calling user sent, delivered to the sender via the inbox pull.
 */
export interface MessageReceipt { 
    /**
     * ID of the original message being acknowledged.
     */
    messageId: string;
    /**
     * ID of the user who delivered/read the message.
     */
    recipientId: string;
    type: ReceiptType;
    /**
     * Signature over (messageId, type, originalSenderId) by the recipient\'s identity key (Base64), echoed unaltered from the submitted DeliveryReceipt.
     */
    signature: string;
}



