/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EncryptedMessage } from './encryptedMessage';


/**
 * WS push: a new encrypted message relayed live by the Hub.
 */
export interface MessageEvent { 
    event: MessageEventEventEnum;
    data: EncryptedMessage;
}
export enum MessageEventEventEnum {
    MessageReceived = 'messageReceived'
};



