/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Plaintext delivery hint set by the sender. The Server uses it only to choose the push notification wording and timing: \'message\' = a chat message (default when omitted); \'call\' = a call offer.
 */
export enum MessageHint {

    Message = 'message',

    Call = 'call'
}

