/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventMessageReceipt } from './eventMessageReceipt';


export interface MessageDispatchedPayload { 
    event: MessageDispatchedPayloadEventEnum;
    data: EventMessageReceipt;
}
export enum MessageDispatchedPayloadEventEnum {
    MessageDispatched = 'messageDispatched'
};



