/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EncryptedMessage } from './encryptedMessage';


/**
 * Submits several messages in one call — used by the client to re-submit unconfirmed outbox messages after a detected Server restart. Idempotent per messageId.
 */
export interface MessageBatchRequest { 
    /**
     * The messages to (re)submit, capped per request; the client chunks larger resyncs.
     */
    messages: EncryptedMessage[];
}

