/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A delivery/read acknowledgement for a message the calling user sent, delivered to the sender via the inbox pull.
 */
export interface MessageReceipt { 
    /**
     * ID of the original message being acknowledged.
     */
    messageId: string;
    /**
     * ID of the user who delivered/read the message.
     */
    recipientId: string;
    /**
     * \'delivered\' = received and decrypted; \'read\' = opened by the user.
     */
    type: MessageReceiptTypeEnum;
}
export enum MessageReceiptTypeEnum {
    Delivered = 'delivered',
    Read = 'read'
};



