/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageAcknowledgement } from './messageAcknowledgement';


export interface MessageDispatchedPayload { 
    event: string;
    data: MessageAcknowledgement;
}

