/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AcceptedResponse } from './acceptedResponse';


export interface MessageBatchResponse { 
    /**
     * Per-message acceptance result, in request order.
     */
    results: Array<AcceptedResponse>;
    /**
     * Epoch milliseconds at which this Server process started (carried once for the whole batch).
     */
    serverStartedAt: number;
}

