/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Signal one-time pre-key, consumed once when a peer opens a session.
 */
export interface OneTimePreKey { 
    /**
     * Client-assigned id of this one-time pre-key.
     */
    keyId: number;
    /**
     * Curve25519 one-time pre-key public key (Base64).
     */
    publicKey: string;
}

