/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Client -> Hub: application-level liveness probe sent after a resume; the Hub replies with a Pong.
 */
export interface PingCommand { 
    type: PingCommandTypeEnum;
}
export enum PingCommandTypeEnum {
    Ping = 'ping'
};



