/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Hub -> client: reply to a Ping, proving the socket is alive.
 */
export interface PongEvent { 
    type: PongEventTypeEnum;
}
export enum PongEventTypeEnum {
    Pong = 'pong'
};



