/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OneTimePreKeyDto } from './oneTimePreKeyDto';


/**
 * Replenishes the caller\'s pool of one-time pre-keys when it runs low.
 */
export interface PreKeysUploadRequest { 
    /**
     * Additional one-time pre-keys to append to the caller\'s pool.
     */
    oneTimePreKeys: Array<OneTimePreKeyDto>;
}

