/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How many one-time pre-keys the caller still has in the directory, so the client can top up below a threshold.
 */
export interface PreKeyCountResponse { 
    /**
     * Remaining one-time pre-keys in the caller\'s pool.
     */
    count: number;
}

