/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Live presence of a watched contact: online/offline
 */
export enum PresenceStatus {

    Online = 'online',

    Offline = 'offline'
}

