/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Client -> Hub: stop receiving a contact\'s state.
 */
export interface PresenceUnsubscribeCommand { 
    type: PresenceUnsubscribeCommandTypeEnum;
    /**
     * The contact to stop watching.
     */
    userId: string;
}
export enum PresenceUnsubscribeCommandTypeEnum {
    PresenceUnsubscribe = 'presence_unsubscribe'
};



