/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Client -> Hub: start receiving a contact\'s online/typing state.
 */
export interface PresenceSubscribeCommand { 
    type: PresenceSubscribeCommandTypeEnum;
    /**
     * The contact to watch.
     */
    userId: string;
}
export enum PresenceSubscribeCommandTypeEnum {
    PresenceSubscribe = 'presence_subscribe'
};



