/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PresenceStatus } from './presenceStatus';


/**
 * WS push: the current or updated online/offline state of a contact the client subscribed to via presenceSubscribe.
 */
export interface PresenceEvent { 
    type: PresenceEventTypeEnum;
    /**
     * The watched contact this state refers to.
     */
    userId: string;
    status: PresenceStatus;
}
export enum PresenceEventTypeEnum {
    Presence = 'presence'
};



