/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A user\'s public profile as served by the directory: the display name and avatar shown to other users. Contains no roles or private account data.
 */
export interface PublicUser { 
    /**
     * The user id this profile belongs to.
     */
    id: string;
    /**
     * The user\'s public display name.
     */
    username?: string;
    /**
     * URL of the user\'s avatar image, if set.
     */
    avatarUrl?: string;
}

