/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SignedPreKey } from './signedPreKey';
import { OneTimePreKey } from './oneTimePreKey';


/**
 * A user\'s Signal pre-key bundle as served by the directory: identity, registration id, signed pre-key, and at most one one-time pre-key (absent when the pool is exhausted).
 */
export interface PublicKeySet { 
    /**
     * The user\'s Signal registration id.
     */
    registrationId: number;
    /**
     * Long-lived Curve25519 identity public key (Base64).
     */
    identityKey: string;
    signedPreKey: SignedPreKey;
    oneTimePreKey?: OneTimePreKey;
    /**
     * Epoch milliseconds when this bundle was uploaded to the directory.
     */
    uploadedAt: number;
}

