/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeysResponse } from './keysResponse';


export interface PublicKeysBatchResponse { 
    results: KeysResponse[];
}

