/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicKeySet { 
    /**
     * ECDSA P-256 public signing key (Base64 SPKI).
     */
    signingPublicKey: string;
    /**
     * ECDH P-256 public encryption key (Base64 SPKI).
     */
    encryptionPublicKey: string;
    /**
     * Epoch milliseconds when these public keys were uploaded to the directory.
     */
    uploadedAt: number;
}

