/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The client keys of a Web Push (VAPID) subscription, used by the Server to encrypt push payloads end-to-end to the browser push service.
 */
export interface PushSubscriptionKeys { 
    /**
     * The subscription\'s P-256 ECDH public key (Base64url), as produced by the browser PushManager.
     */
    p256dh: string;
    /**
     * The subscription\'s auth secret (Base64url), as produced by the browser PushManager.
     */
    auth: string;
}

