/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PushSubscriptionKeys } from './pushSubscriptionKeys';


/**
 * A browser Web Push (VAPID) subscription registered by an authenticated client so the Server can wake an offline recipient.
 */
export interface PushSubscription { 
    /**
     * The push service endpoint URL the Server delivers encrypted pushes to.
     */
    endpoint: string;
    /**
     * Optional epoch milliseconds at which the subscription expires, if the browser provided one.
     */
    expirationTime?: number;
    keys: PushSubscriptionKeys;
}

