/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReceiptData { 
    /**
     * ID of the original message this receipt refers to.
     */
    messageId: string;
    /**
     * ID of the user who delivered/read the message (the original recipient).
     */
    recipientId: string;
}

