/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EncryptedMessage } from './encryptedMessage';


export interface ReceiveMessagePayload { 
    event: ReceiveMessagePayloadEventEnum;
    data: EncryptedMessage;
}
export enum ReceiveMessagePayloadEventEnum {
    MessageReceived = 'messageReceived'
};



