/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptType } from './receiptType';


export interface ReceiptData { 
    /**
     * ID of the original message this receipt refers to.
     */
    messageId: string;
    /**
     * ID of the user who delivered/read the message (the original recipient).
     */
    recipientId: string;
    type: ReceiptType;
    /**
     * Signature over (messageId, type, originalSenderId) by the recipient\'s identity key (Base64), relayed unaltered from the submitted DeliveryReceipt.
     */
    signature: string;
}



