/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptData } from './receiptData';


/**
 * WS push: a delivery/read notification relayed live to the original sender.
 */
export interface ReceiptEvent { 
    event: ReceiptEventEventEnum;
    data: ReceiptData;
}
export enum ReceiptEventEventEnum {
    MessageDelivered = 'messageDelivered',
    MessageRead = 'messageRead'
};



