/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeliveryReceipt } from './deliveryReceipt';


/**
 * Submits several signed receipts in one call.
 */
export interface ReceiptBatchRequest { 
    /**
     * The signed receipts to record, capped per request.
     */
    receipts: DeliveryReceipt[];
}

