/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * \'delivered\' = the recipient device received and decrypted the message; \'read\' = the user opened it.
 */
export enum ReceiptType {

    Delivered = 'delivered',

    Read = 'read'
}

