/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Body of a 401 from /auth/refresh. \'revoked\' means a newer login took over the single active device, on which the client wipes its local E2E identity keys; the other reasons just require re-authentication.
 */
export interface RefreshError { 
    /**
     * \'revoked\' = invalidated by a newer login (single-active-device takeover); \'expired\' = refresh token past expiry; \'invalid\' = malformed/missing or session mismatch.
     */
    reason: RefreshErrorReasonEnum;
}
export enum RefreshErrorReasonEnum {
    Revoked = 'revoked',
    Expired = 'expired',
    Invalid = 'invalid'
};



