/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EncryptedMessage } from './encryptedMessage';


export interface SendMessagePayload { 
    action: SendMessagePayloadActionEnum;
    data: EncryptedMessage;
}
export enum SendMessagePayloadActionEnum {
    SendMessage = 'sendMessage'
};



