/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A Signal signed pre-key: a medium-lived Curve25519 public key signed by the identity key.
 */
export interface SignedPreKeyDto { 
    /**
     * Client-assigned id of this signed pre-key.
     */
    keyId: number;
    /**
     * Curve25519 signed pre-key public key (Base64).
     */
    publicKey: string;
    /**
     * Identity-key signature over the signed pre-key public key (Base64).
     */
    signature: string;
}

