/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Server acknowledgement of a persisted telemetry batch.
 */
export interface TelemetryAcceptedResponse { 
    /**
     * The batch was accepted and written to disk.
     */
    status: TelemetryAcceptedResponseStatusEnum;
    /**
     * Number of LogRecords persisted.
     */
    acceptedCount: number;
}
export enum TelemetryAcceptedResponseStatusEnum {
    Accepted = 'accepted'
};



