/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TelemetryLogRecord } from './telemetryLogRecord';
import { TelemetryResource } from './telemetryResource';


/**
 * A batch of client OpenTelemetry LogRecords submitted for server-side persistence as JSON lines.
 */
export interface TelemetryLogBatch { 
    resource?: TelemetryResource;
    /**
     * The captured LogRecords, capped per request.
     */
    logRecords: TelemetryLogRecord[];
}

