/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A single OpenTelemetry LogRecord captured on the client. Carries only redacted diagnostics — never end-to-end message content, keys, or tokens.
 */
export interface TelemetryLogRecord { 
    /**
     * Event time as OTel Unix nanoseconds — an int64 encoded as a decimal string (OTLP/JSON convention), avoiding client-side number precision loss.
     */
    timeUnixNano: string;
    /**
     * OTel severity text. Only warnings and errors are captured.
     */
    severityText: TelemetryLogRecordSeverityTextEnum;
    /**
     * OTel SeverityNumber (WARN=13, ERROR=17).
     */
    severityNumber?: number;
    /**
     * The log message body (redacted).
     */
    body: string;
    /**
     * Redacted OTel attributes (e.g. route, error.name, error.stack, http.status). Must never contain plaintext message content, ciphertext, keys, or auth tokens.
     */
    attributes?: Record<string, any>;
}
export enum TelemetryLogRecordSeverityTextEnum {
    Warn = 'WARN',
    Error = 'ERROR'
};



