/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * OpenTelemetry resource attributes describing the client that produced the log records. Attached once per batch and merged into every persisted LogRecord.
 */
export interface TelemetryResource { 
    /**
     * OTel service.name of the emitting client (e.g. \'fourletters-gui\').
     */
    serviceName?: string;
    /**
     * OTel service.version — the client app/build version.
     */
    serviceVersion?: string;
    /**
     * Client-generated session id correlating all records from one app run. Never a user identifier.
     */
    sessionId?: string;
    /**
     * Browser user agent string of the client.
     */
    userAgent?: string;
}

