/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * WS push: a watched contact is currently typing.
 */
export interface TypingEvent { 
    type: TypingEventTypeEnum;
    /**
     * The contact who is typing.
     */
    userId: string;
}
export enum TypingEventTypeEnum {
    Typing = 'typing'
};



