/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * WS push: an authenticated user is typing. Direct events are delivered only to the recipient; group events carry groupId and are delivered to group typing watchers. No persistence or replay.
 */
export interface TypingEvent { 
    type: TypingEventTypeEnum;
    /**
     * The sender who is typing, derived from the authenticated session.
     */
    userId: string;
    /**
     * The group being typed in. Absent for direct typing.
     */
    groupId?: string;
}
export enum TypingEventTypeEnum {
    Typing = 'typing'
};



