/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Client -> Hub: \'I am typing in my active chat.\' The Hub derives the sender id from the authenticated session and relays it to that user\'s watchers.
 */
export interface TypingCommand { 
    type: TypingCommandTypeEnum;
}
export enum TypingCommandTypeEnum {
    Typing = 'typing'
};



