/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Client -> Hub: announce typing to exactly one destination: recipientId for a direct chat or groupId for a group. The Hub validates destination exclusivity and derives the sender from authentication.
 */
export interface TypingCommand { 
    type: TypingCommandTypeEnum;
    /**
     * Direct recipient; routed to typing.user.<recipientId>.
     */
    recipientId?: string;
    /**
     * Group destination; routed to typing.group.<groupId>.
     */
    groupId?: string;
}
export enum TypingCommandTypeEnum {
    Typing = 'typing'
};



