/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Client -> Hub: watch typing in a group.
 */
export interface TypingGroupSubscribeCommand { 
    type: TypingGroupSubscribeCommandTypeEnum;
    groupId: string;
}
export enum TypingGroupSubscribeCommandTypeEnum {
    TypingGroupSubscribe = 'typing_group_subscribe'
};



