/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Client -> Hub: stop watching group typing.
 */
export interface TypingGroupUnsubscribeCommand { 
    type: TypingGroupUnsubscribeCommandTypeEnum;
    groupId: string;
}
export enum TypingGroupUnsubscribeCommandTypeEnum {
    TypingGroupUnsubscribe = 'typing_group_unsubscribe'
};



