/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WrappedGroupKey } from './wrappedGroupKey';


/**
 * Owner-only roster change. Adding and/or removing members always rotates: the body carries the new epoch\'s full wrapped-key set for the resulting roster. Compare-and-swap on epoch.
 */
export interface UpdateMembersRequest { 
    /**
     * User ids to add to the roster.
     */
    add?: Array<string>;
    /**
     * User ids to remove from the roster.
     */
    remove?: Array<string>;
    /**
     * The new epoch (must equal current epoch + 1). Rejected with 409 on mismatch.
     */
    epoch: number;
    /**
     * The new epoch key wrapped to exactly the resulting roster (after add/remove).
     */
    keys: Array<WrappedGroupKey>;
}

