/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Owner-only partial update of a group\'s metadata. Only the provided fields are changed.
 */
export interface UpdateGroupRequest { 
    /**
     * New group name (plaintext). Omit to leave unchanged.
     */
    name?: string;
    /**
     * Base64 data URL to set the avatar, an empty string to clear it, or omit to leave it unchanged.
     */
    avatarUrl?: string;
}

