/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Owner-only roster change.
 */
export interface UpdateMembersRequest { 
    /**
     * User ids to add to the roster.
     */
    add?: string[];
    /**
     * User ids to remove from the roster.
     */
    remove?: string[];
}

