/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserResponse { 
    id: string;
    username: string;
    avatarUrl?: string;
    /**
     * List of user permissions/roles for RBAC.
     */
    roles: string[];
}

