/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicUser } from './publicUser';


/**
 * Public profiles for a batch of requested user ids. Missing/unknown ids are simply omitted.
 */
export interface UserBatchResponse { 
    users: PublicUser[];
}

