/**
 * Shared Data Models for Fourletters API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The group\'s symmetric epoch key wrapped (encrypted) to a single member\'s encryption public key. The Server stores and relays this opaque blob but never the group key itself.
 */
export interface WrappedGroupKey { 
    /**
     * The member this blob is encrypted for.
     */
    recipientId: string;
    /**
     * The group epoch key wrapped to the member\'s ECDH encryption key (Base64, same ephemeral-ECDH + AES-GCM envelope used for 1:1 payloads).
     */
    wrappedKey: string;
}

